apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: reana-v2
    meta.helm.sh/release-namespace: reana
    traefik.frontend.entryPoints: http,https
  name: <helm-release-name>-ingress
  namespace: reana
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: <helm-release-name>-server
            port:
              number: 80
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: <helm-release-name>-server
            port:
              number: 80
        path: /oauth
        pathType: Prefix
      - backend:
          service:
            name: <helm-release-name>-ui
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - secretName: <helm-release-name>-tls-secret
status:
  loadBalancer:
    ingress:
    - ip: <lb-ip>
