name: REANA Workflow Test

on:
  workflow_dispatch:
  
jobs:
  run-wf:
    runs-on: ubuntu-latest
    steps:
      - name: Install reana-client
        run: |
          pip install reana-client
      - name: Setup env
        run: |
          export REANA_SERVER_URL=${{ secrets.REANA_URL }}
          export REANA_ACCESS_TOKEN=${{ secrets.REANA_TK }}
          git clone https://github.com/reanahub/reana-demo-root6-roofit
      - name: Test connection
        run: reana-client ping
      - name: Run workflow
        run: |
          cd reana-demo-root6-roofit
          reana-client run -w root6-roofit
          
